<a href="https://colab.research.google.com/github/Tahmidro/phitronNotebooks/blob/main/module_14_logistic_regression_implementation_using_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder, MinMaxScaler,OrdinalEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [18]:
df=pd.read_csv("titanic_data_updated.csv")
df.sample(6)

     PassengerId Survived  Pclass  ...     Fare Cabin  Embarked
775          776       no   third  ...   7.7500   NaN         S
79            80      yes   third  ...  12.4750   NaN         S
367          368      yes   third  ...   7.2292   NaN         C
248          249      yes   first  ...  52.5542   D35         S
147          148       no   third  ...  34.3750   NaN         S
312          313       no  second  ...  26.0000   NaN         S

[6 rows x 12 columns]

In [20]:
df["FamiliSize"]=df["SibSp"]+df["Parch"]+1
df['Cabin']=df['Cabin'].fillna("Missing")
df["Deck"]=df["Cabin"].astype(str).str[0]
df.sample(6)

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [22]:
X=df.drop(["Survived"],axis=1)
y=df['Survived']

Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)